//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace POIS1
{
    public partial class Invoice
    {
        public int Invoice_id { get; set; }
        public int PurchaseOrderID { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public Nullable<System.DateTime> DateForPayment { get; set; }
        public Nullable<int> Vendors_id { get; set; }
        public string Invoice_description { get; set; }
        public int total { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> PurchaseOrderNumber { get; set; }

        public virtual InvoiceStatu InvoiceStatu { get; set; }
        public virtual LogPurchaseOrder LogPurchaseOrder { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
